### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by yustme** [keboola/phpstorm-shared-configuration#1]
Našel jsem pár věcí, které mi chybí při auto formátování a neodpovídájí pak phpcs 

- [ ] prázdný řádek na konci souboru
 - [ ] za přetypováním se nedělá mezera `(int)"123"`, ale má být `(int) 123`
 - [ ] návratový typ a otevírací závorka není na jednom řádku, ale závorka je na novém řádku

**Comment by tomasfejfar** [comment]
![image](https://user-images.githubusercontent.com/642928/56897270-55450e00-6a8e-11e9-8b0d-5bd8b36d8aa7.png)
 Mezera za přetypováním funguje. Zkontroluj si prosím 2x, že to máš opravdu nastavené a zapnuté.

**Comment by tomasfejfar** [comment]
Závorka na novém řádku po typu je OK IMHO:
![image](https://user-images.githubusercontent.com/642928/56897463-ea480700-6a8e-11e9-897a-ac866955d4d9.png)

**Comment by yustme** [comment]
Né vždycky 
![Snímek z 2019-04-29 14-56-35](https://user-images.githubusercontent.com/5272798/56897548-1499c480-6a8f-11e9-9949-fb209cf281d3.png)

**Comment by tomasfejfar** [comment]
![keboola](https://user-images.githubusercontent.com/642928/56897832-cfc25d80-6a8f-11e9-80f1-4566ccd99a40.gif)

**Comment by tomasfejfar** [comment]
![image](https://user-images.githubusercontent.com/642928/56897928-1748e980-6a90-11e9-9a54-f53bf060d917.png)

**Comment by tomasfejfar** [comment]
Máš to nastavené jinak u tebe?

**Comment by tomasfejfar** [comment]
Pošli mi tenhle stejný screenshot pls

**Comment by yustme** [comment]
![Snímek z 2019-04-29 15-11-35](https://user-images.githubusercontent.com/5272798/56898348-1e242c00-6a91-11e9-8983-4fdda1472610.png)

**Comment by tomasfejfar** [comment]
No, tak když nemáš nastavený ten Keboola CS, tak to nemůže fungovat :)

**Comment by yustme** [comment]
Jo už to frčí. Bylo by fajn to napsat někam do readme, že je to potřeba přepnout. Já jsem myslel, že je všechno automaticky.

Díky
